name: Recent Activity

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_KEY }}
        with:
          COMMIT_MSG: 'Update recent activity'
          MAX_LINES: 5