name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Activity
        uses: Readme-Workflows/recent-activity
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_KEY }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"

      - name: Commit & Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Updated README with latest stats"
          git push
